-- MySQL Script generated by MySQL Workbench
-- 2016年12月22日 星期四 10时54分14秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `MS_Database`.`StockInformation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS_Database`.`StockInformation` (
  `Timestamp` DATE NOT NULL,
  `Price` FLOAT NULL,
  `Quantity` FLOAT NULL,
  `High` FLOAT NULL,
  `Low` FLOAT NULL,
  PRIMARY KEY (`Timestamp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MS_Database`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS_Database`.`Order` (
  `OrderID` VARCHAR(45) NOT NULL,
  `TransactionTime` DATE NULL,
  `Side` INT NULL,
  `OrderType` INT NULL,
  `OrderPrice` FLOAT NULL,
  `OrderQuantity` FLOAT NULL,
  `LastStatus` INT NULL,
  `MaturityDate` DATE NULL,
  `QuantityFilled` FLOAT NULL,
  `AveragePrice` FLOAT NULL,
  `StockTicker` VARCHAR(45) NULL,
  PRIMARY KEY (`OrderID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MS_Database`.`OrderResult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MS_Database`.`OrderResult` (
  `OrderID` VARCHAR(45) NOT NULL,
  `OrderTransactionTime` DATE NULL,
  `ResultTime` DATE NULL,
  `Quantity` FLOAT NULL,
  `Price` FLOAT NULL,
  PRIMARY KEY (`OrderID`),
  CONSTRAINT `OrderID`
    FOREIGN KEY (`OrderID`)
    REFERENCES `MS_Database`.`Order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

